#include <furi.h>
#include <gui/gui.h>
#include <gui/icon_i.h>
#include <gui/view_dispatcher.h>
#include <gui/scene_manager.h>
#include <gui/modules/popup.h>
/* generated by fbt from .png files in images folder */
#include <fancy_remote_icons.h>
#include <gui/modules/submenu.h>
#include <gui/modules/button_panel.h>
#include <gui/icon.h>

typedef enum {
    Scene_MainMenu,
    Scene_PopupOne,
    Scene_PopupTwo,
    Scene_RemotePanel,
    Scene_count
} Scene;

typedef enum {
    FView_Menu,
    FView_Popup,
    FView_ButtonPanel
} FView;

typedef struct {
    SceneManager* scene_manager;
    ViewDispatcher* view_dispatcher;
    Submenu* submenu;
    Popup* popup;
    ButtonPanel* buttonPanel;
} FancyRemote;

typedef enum {
    Event_ShowPopupOne,
    Event_ShowPopupTwo,
    Event_ShowRemotePanel
} Event;
typedef enum {
    MenuSelection_One,
    MenuSelection_Two,
    MenuSelection_Three
} MenuSelection;

void fancy_remote_menu_callback_main_menu(void* context, uint32_t index) {
    FancyRemote* app = context;
    switch(index) {
    case MenuSelection_One:
        scene_manager_handle_custom_event(app->scene_manager, Event_ShowPopupOne);
        break;
    case MenuSelection_Two:
        scene_manager_handle_custom_event(app->scene_manager, Event_ShowPopupTwo);
        break;
    case MenuSelection_Three:
        scene_manager_handle_custom_event(app->scene_manager, Event_ShowRemotePanel);
        break;
    }
}
void fancy_remote_scene_on_enter_MainMenu(void* context) {
    FancyRemote* app = context;

    submenu_reset(app->submenu);
    submenu_add_item(
        app->submenu, "option #1", MenuSelection_One, fancy_remote_menu_callback_main_menu, app);
    submenu_add_item(
        app->submenu, "option #2", MenuSelection_Two, fancy_remote_menu_callback_main_menu, app);
    submenu_add_item(
        app->submenu,
        "option #3 (mine)",
        MenuSelection_Three,
        fancy_remote_menu_callback_main_menu,
        app);
    view_dispatcher_switch_to_view(app->view_dispatcher, FView_Menu);
}
bool fancy_remote_scene_on_event_MainMenu(void* context, SceneManagerEvent event) {
    bool consumed = false;
    FancyRemote* app = context;
    switch(event.type) {
    case SceneManagerEventTypeCustom:
        switch(event.event) {
        case Event_ShowPopupOne:
            scene_manager_next_scene(app->scene_manager, Scene_PopupOne);
            consumed = true;
            break;
        case Event_ShowPopupTwo:
            scene_manager_next_scene(app->scene_manager, Scene_PopupTwo);
            consumed = true;
            break;
        case Event_ShowRemotePanel:
            scene_manager_next_scene(app->scene_manager, Scene_RemotePanel);
            consumed = true;
        }
        break;
    default:
        consumed = false;
    }
    return consumed;
}
void fancy_remote_scene_on_exit_MainMenu(void* context) {
    FancyRemote* app = context;

    submenu_reset(app->submenu);
}
void fancy_remote_scene_on_enter_PopupOne(void* context) {
    FancyRemote* app = context;
    popup_reset(app->popup);
    popup_set_context(app->popup, app);
    popup_set_header(app->popup, "Pop#1", 60, 10, AlignCenter, AlignTop);
    popup_set_icon(app->popup, 10, 10, NULL);
    popup_set_text(app->popup, "ONE DOWN<>PLEASE WORK", 60, 20, AlignLeft, AlignTop);
    view_dispatcher_switch_to_view(app->view_dispatcher, FView_Popup);
}
bool fancy_remote_scene_on_event_PopupOne() {
    return false;
}
void fancy_remote_scene_on_exit_PopupOne(void* context) {
    FancyRemote* app = context;
    popup_reset(app->popup);
}

void fancy_remote_scene_on_enter_PopupTwo(void* context) {
    FancyRemote* app = context;
    popup_reset(app->popup);
    popup_set_context(app->popup, app);
    popup_set_header(app->popup, "Pop#2", 60, 10, AlignCenter, AlignTop);
    popup_set_icon(app->popup, 10, 10, NULL);
    popup_set_text(app->popup, "TWO DOWN<>PLEASE WORK", 60, 20, AlignLeft, AlignTop);
    view_dispatcher_switch_to_view(app->view_dispatcher, FView_Popup);
}
bool fancy_remote_scene_manager_navigation_event_callback(void* context) {
    FancyRemote* app = context;
    return scene_manager_handle_back_event(app->scene_manager);
}
void backToHome(void* context, uint32_t index) {
    (void)index;
    fancy_remote_scene_manager_navigation_event_callback(context);
}
void addGeneric(void* context, int Vx, int Vy, int x, int y) {
    FancyRemote* app = context;
    button_panel_add_item(
        app->buttonPanel, 0, Vx, Vy, x, y, &I_fancy_remote, &I_selected, backToHome, context);
}
void addVolumeButtons(void* context, int Vx, int Vy, int x, int y, void* doUp, void* doDown) {
    /*
    in origional the text is at (35,66), volume up is at (38,53), and volume down is at (38,91)
    so relative measurments are: volUp:(+3,+0),text:(+0,+13),volDown(+3,+25)
    */
    FancyRemote* app = context;
    button_panel_add_item(
        app->buttonPanel, 0, Vx, Vy, x + 3, y, &I_volup_24x21, &I_volup_hover_24x21, doUp, context);
    button_panel_add_icon(app->buttonPanel, x, y + 13, &I_vol_tv_text_29x34);
    button_panel_add_item(
        app->buttonPanel,
        0,
        Vx,
        Vy + 1,
        x + 3,
        y + 38,
        &I_voldown_24x21,
        &I_voldown_hover_24x21,
        doDown,
        context);
}
void fancy_remote_scene_on_enter_RemotePanel(void* context) {
    FancyRemote* app = context;
    button_panel_reset(app->buttonPanel);
    button_panel_reserve(app->buttonPanel, 1, 2);
    addVolumeButtons(context, 0, 0, 17, 25, backToHome, backToHome);
    view_dispatcher_switch_to_view(app->view_dispatcher, FView_ButtonPanel);
}
bool fancy_remote_scene_on_event_PopupTwo() {
    return false;
}
bool fancy_remote_scene_on_event_RemotePanel() {
    return false;
}
void fancy_remote_scene_on_exit_PopupTwo(void* context) {
    FancyRemote* app = context;
    popup_reset(app->popup);
}
void fancy_remote_scene_on_exit_RemotePanel(void* context) {
    FancyRemote* app = context;
    button_panel_reset(app->buttonPanel);
}
/*on enter handlers(being declared before use)*/
void (*const fancy_remote_scene_on_enter_handlers[])(void*) = {
    fancy_remote_scene_on_enter_MainMenu,
    fancy_remote_scene_on_enter_PopupOne,
    fancy_remote_scene_on_enter_PopupTwo,
    fancy_remote_scene_on_enter_RemotePanel};

bool (*const fancy_remote_scene_on_event_handlers[])(void*, SceneManagerEvent) = {
    fancy_remote_scene_on_event_MainMenu,
    fancy_remote_scene_on_event_PopupOne,
    fancy_remote_scene_on_event_PopupTwo,
    fancy_remote_scene_on_event_RemotePanel};
void (*const fancy_remote_scene_on_exit_handlers[])(void*) = {
    fancy_remote_scene_on_exit_MainMenu,
    fancy_remote_scene_on_exit_PopupOne,
    fancy_remote_scene_on_exit_PopupTwo,
    fancy_remote_scene_on_exit_RemotePanel};
//bringing it all together is this thing
const SceneManagerHandlers fancy_remote_scene_event_handlers = {
    .on_enter_handlers = fancy_remote_scene_on_enter_handlers,
    .on_event_handlers = fancy_remote_scene_on_event_handlers,
    .on_exit_handlers = fancy_remote_scene_on_exit_handlers,
    .scene_num = Scene_count};

void fancy_remote_scene_manager_init(FancyRemote* app) {
    app->scene_manager = scene_manager_alloc(&fancy_remote_scene_event_handlers, app);
}
bool fancy_remote_scene_manager_custom_event_callback(void* context, uint32_t custom_event) {
    FancyRemote* app = context;
    return scene_manager_handle_custom_event(app->scene_manager, custom_event);
}
void fancy_remote_view_dispatcher_init(FancyRemote* app) {
    app->view_dispatcher = view_dispatcher_alloc();
    app->submenu = submenu_alloc();
    app->popup = popup_alloc();
    app->buttonPanel = button_panel_alloc();
    view_dispatcher_set_event_callback_context(app->view_dispatcher, app);
    view_dispatcher_set_custom_event_callback(
        app->view_dispatcher, fancy_remote_scene_manager_custom_event_callback);

    view_dispatcher_set_navigation_event_callback(
        app->view_dispatcher, fancy_remote_scene_manager_navigation_event_callback);
    view_dispatcher_add_view(app->view_dispatcher, FView_Menu, submenu_get_view(app->submenu));
    view_dispatcher_add_view(app->view_dispatcher, FView_Popup, popup_get_view(app->popup));
    view_dispatcher_add_view(
        app->view_dispatcher, FView_ButtonPanel, button_panel_get_view(app->buttonPanel));
}

FancyRemote* fancy_remote_init() {
    FancyRemote* app = malloc(sizeof(FancyRemote));
    fancy_remote_scene_manager_init(app);
    fancy_remote_view_dispatcher_init(app);
    return app;
}
//frees all data when done
void fancy_remote_free(FancyRemote* app) {
    scene_manager_free(app->scene_manager);
    view_dispatcher_remove_view(app->view_dispatcher, FView_Menu);
    view_dispatcher_remove_view(app->view_dispatcher, FView_Popup);
    view_dispatcher_remove_view(app->view_dispatcher, FView_ButtonPanel);
    view_dispatcher_free(app->view_dispatcher);
    submenu_free(app->submenu);
    popup_free(app->popup);
    button_panel_free(app->buttonPanel);
    free(app);
}
int32_t fancy_remote_app(/*void* p*/) {
    FancyRemote* app = fancy_remote_init();
    Gui* gui = furi_record_open(RECORD_GUI);
    view_dispatcher_attach_to_gui(app->view_dispatcher, gui, ViewDispatcherTypeFullscreen);
    scene_manager_next_scene(app->scene_manager, Scene_MainMenu);
    //this is the main loop
    view_dispatcher_run(app->view_dispatcher);

    //this runs after program ends
    fancy_remote_free(app);
    return 0;
}
